	AREA LAB, CODE, READONLY
	MOV R0, #0xF2
	MOV R1, #0xE3
	MUL R2,R1,R0
	; FOR ASSIGNING REG WITH NUMBER GREATER THAN 8 BIT,
	; USE LDR INSTEAD OF MOV 
	; FOR LONG MULTIPLICATION WITH MORE THAN 16BIT
	; UMULL R3,R2,R1,R0	; HERE R3 STORES THE LOWER 2 BYTES(16bit), R2 THE UPPER 2 BYTES
L	B L
	END
;0XF2 x 0XE3 = 0XD696--> STORED IN R2 REG