	AREA FASTGPIO, CODE, READONLY
; SCS REGISTER [0:1] BITS SELECT MODE OF OPERATION OF PORT 0 AND 1
; WHEN HIGH, THE RESPECTIVE PORT IS SET AS FAST GPIO PIN
SCS			EQU 0XE01FC1A0	; SYSTEM CONTROL AND STATUS REGISTER
FIO0DIR		EQU 0X3FFFC000
FIO0MASK 	EQU 0X3DDDC010	; TO MASK THE PIN FROM RECEIVING ANY SIGNALS
FIO0SET 	EQU 0X3FFFC018
FIO0CLR		EQU 0X3FFFC01C
FIO0PIN		EQU 0X3FFFC014
	
		LDR R0, =SCS
		LDR R1, =0X00000001
		STR R1, [R0]		; SET PORT 0 AS FAST GPIO PIN
		LDR R0, =FIO0DIR
		LDR R1, =0XFFFFFFFF	; SET ALL PORT0 PINS AS OUTPUT
		STR R1, [R0]
; GENERATES A SQUARE WAVE AT PORT 0
START	LDR R2, =FIO0SET
		STR R1, [R2]
		BL DELAY
		LDR R3, =FIO0CLR
		STR R1, [R3]
		BL DELAY
		B START

DELAY	LDR R4, =0X00FFFFFF
L		SUBS R4, R4, #0X01
		BNE L
		BX LR
	END
	
		